### PR TITLE
Attribute Value + Manipulate Children

### PR DESCRIPTION
**Pull request by bgisme**
Get attribute value with key

```swift
func value(_ key: String) -> String?
```

This would make finding an attribute value very compact and convenient

Add [Tag] to children with TagBuilder parameter

```swift
public func insert(at i: Int? = nil, if condition: Bool = true, @TagBuilder children: () -> [Tag]) -> Self
public func append(_ condition: Bool = true, @TagBuilder children: () -> [Tag]) -> Self
```

One more option when declaring a Tag. Right now it's either Tag(...) or Tag {...} This way is both Tag(...).insert{...}

Also, it would allow you to write func() calls on a Tag before declaring children. For example, instead of...

```swift
Div {
     // ... a huge hierarchy making me lose track of parent's closing bracket
}
.func()
.anotherFunc()
.anotherFunc()
```

You could put the func() calls next to the tag declaration. And then attributes are listed closer to the parent.

```swift
Div()
     .func()
     .anotherFunc()
     .anotherFunc()
     .append {
          // ... a huge hierarchy that seems better placed in code
     }
```

• Remove children at index

```swift
public func remove(at i: Int, if condition: Bool = true) -> Self
```

If children can be added, it seems only natural to also remove

### CODE REVIEW

**Comment by tib** [comment]
Sorry, could you give me a brief explanation about this PR? I can see what the functions are doing, but I'd like to know a bit more about the reasons why we should have them... thank you.

**Comment by bgisme** [comment]
Many apologies.

I attached a lengthy explanation in the PR request notes. Especially for inserting and appending children.

Do you need more detail? Are my notes confusing as to why I think they are important?

Thanks.

**Comment by tib** [comment]
Yeah, it was a bit confusing, because of the strange syntax format, I fixed your comment, now it's more readable. :)

Anyway, I like this idea, maybe the naming should be `insertChildren`, `appendChildren`, but I'm not sure just yet.
Same thing applies for the remove -> removeChild ?

Also a suggestion for the `value` function -> `attributeValue(for: "key")`

Please give me a day or two to think about this. :)

**Comment by bgisme** [comment]
Sorry about that.

Didn’t realize there were tags for swift code.

Now I know!

Thanks for your cogitation...

BG

**Comment by bgisme** [comment]
One quick thought on the naming conventions...

I've been reading a lot that Swift function names should be very light. And read like extremely thin glue between the logic and variables. That unnecessary labeling or declaratives should be avoided. And to let the supplied variables play a part in the function declaration.

For example...

’’’swift
func value(_ attributeKey: String) -> String?
’’’

... reads like this ...

’’’swift
node.value("class")
’’’

... is lighter and less redundant than ...

’’’swift
node.attributeValue("class")
’’’

The value of the parameter "class" makes the 'attribute' part of the func() name less necessary. And reads redundantly when the code is littered with them.

I see it a lot in init()s ...

’’’swift
init(true)
init("Some string")
init(myInt)
’’’

... versus ...

’’’swift
initBool(false)
init(bool: false)
initString("Some string")
init(string: "Some string")
initInt(myInt)
init(int: myInt)
’’’

And in the case of the children func()s, 'insert' and 'append' seem perfectly clear when followed by brackets with child tags.

’’’swift
tag.append {
     childTag
     childTag
     childTag
}
’’’

While...

’’’swift
tag.insertChildren {
     childTag
     childTag
     childTag
}
’’’

... reads a little like unnecessary labeling. It's clear what's being appended.

The one func() that may benefit from extra clarity is...

’’’swift
tag.removeChildren(at: 5)
’’’

... instead of ...

’’’swift
tag.remove(at: 5)
’’’

That's just my two cents worth.

Happy to call them whatever you like.

**Comment by bgisme** [comment]
Sorry. Must have closed this pull request by accident while I was mucking around.

**Comment by tib** [comment]
I was thinking this PR and I think I need a better understanding to evaluate it properly. Could you give me an example use case when you need to dynamically manipulate the hierarchy? 🤔

**Comment by bgisme** [comment]
Off the top of my head, I can't think of a NEED to dynamically manipulate the hierarchy.

I'm just proposing a more flexible way to initialize a Tag. Instead of having to first declare parameters, then children and then functions afterwards...

```swift
Tag(a, b, c) {
     // children...
}
.class(insert: "slug")
.func(d)
.func(e)
```

Being able to manipulate the children would allow you to put the functions up top and children below.

```swift
Tag(a, b, c) {
.class(insert: "slug")
.func(d)
.func(e)
.append {
     // children...
}
```

That's all. There's no NEED to manipulate children. It's just the only way to achieve what I'm describing. After making lots of custom Tags, I found the initialization can get quite 'syntaxy' and hard to read with parenthesis around parameters that stretch over multiple lines and nesting braces. Yikes.

One last step to cleaning up initialization is to convert parameters into functions. Like so...

```swift
Tag()
.func(a)
.func(b)
.func(c)
.class(insert: "slug")
.func(parameter)
.anotherFunc(parameter)
 {
     // children...
}
```

But the only way to achieve any of this would require being able to manipulate the children.

**Comment by bgisme** [comment]
Hey Tibor.

I'm not sure if you already read my previous comment. Before I re-wrote it several times throughout the week, trying to refine my thinking. It's been hectic and my first drafts were rushed. And I think you only get notified once, the first time I post a comment.

But now I think I've made the best, clearest case I can. And I finally updated the code to reflect it.

If you did not already read my previous comment, then these few sentences are moot.

Thanks!

**Pull request closed without merging**
