### PR TITLE
AttributeKey enum

### PR DESCRIPTION
**Pull request by bgisme**
Add type safety for making Attributes with...

```swift
enum AttributeKey: String {...}
```

Also, I added a function to the previous pull request for getting values with AttributeKey. Since it relies on that one being approved.

```swift
func value(_ key: AttributeKey) -> String? {
    self.value(key.rawValue)
}
```

### CODE REVIEW

**Comment by tib** [comment]
I'm sorry, but this makes no sense to me, there are dedicated functions that you can use to set the appropriate attribute, why should we introduce attribute keys also? 🤔

**Comment by bgisme** [comment]
Sorry. I should have included examples.

And I just finished typing out a long explanation of situations where they could improve parameter safety...

```swift
a.setAttribute("class", "value")
a.setAttribute("clas", "value")
```
... results in ...

```html
<a class='value' clas='value' ><\a>
```
... and tests fail ...

```swift
if let xmlns = svg.value("xmls") {
     ... something important
}
```

But when I took another look at the list of enum cases and realized how many attributes are NOT included, I changed my mind.

Trying to standardize something so extendable is a fools errand.

I've been using them in my code because they're extremely helpful. But just the ones I care about, a tiny subset.

That doesn't scale.

Wah-wah!

I'll remove the func that takes an enum from my other pull request.

:)

**Comment by tib** [comment]
Thank you, I'll have time during the weekend to think about the other PR (busy days). :)

**Comment by bgisme** [comment]
I feel you.

No worries.

And no rush.

**Pull request closed without merging**
